name: Deploy and Check Vercel Deployment

on:
  push:
    branches: ["main", "dev2"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Call Vercel Deploy Hook
        id: deploy_hook
        run: |
          response=$(curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{"name": "deploy"}')
          echo "Response: $response"
          echo "::set-output name=deployment_url::$(echo $response | jq -r '.url')"

      - name: Wait for Deployment to Finish
        id: wait
        run: |
          deployment_url="${{ steps.deploy_hook.outputs.deployment_url }}"
          echo "Deployment URL: $deployment_url"
          for i in {1..10}; do
            deployment_info=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_API_TOKEN }}" "https://api.vercel.com/v1/deployments?url=${deployment_url}")
            state=$(echo $deployment_info | jq -r '.deployments[0].state')
            echo "Current state: $state"
            if [ "$state" == "READY" ]; then
              echo "Deployment is ready."
              break
            fi
            sleep 25
          done

      - name: Call register scheduled push notification API
        run: |
          curl -X POST https://skin-check-dev.vercel.app/api/send-scheduled-fcm \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
