name: Deploy and Check Vercel Deployment

on:
  push:
    branches: ["main", "dev2"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Call Vercel Deploy Hook
        id: deploy_hook
        run: |
          response=$(curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{"name": "deploy"}')
          echo "Response: $response"

      - name: Wait for Deployment to Finish
        id: wait
        run: |
          for i in {1..24}; do
            deployment_info=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_API_TOKEN }}" "https://api.vercel.com/v13/deployments/skin-check-dev.vercel.app")
            status=$(echo $deployment_info | jq -r '.status')
            echo "Current status: $status"
            if [ "$status" == "READY" ]; then
              echo "Deployment is ready."
              break
            fi
            sleep 10
          done

      - name: Call register scheduled push notification API
        run: |
          curl -X POST https://skin-check-dev.vercel.app/api/send-scheduled-fcm \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
